name: Deploy to WordPress.org Repository

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  deploy_to_wp_repository:
    name: Deploy to WP.org
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: |
        npm install
        npm run build
    # - name: WordPress.org Plugin Deploy
    #   id: deploy
    #   uses: 10up/action-wordpress-plugin-deploy@stable
    #   with:
    #     generate-zip: true
    #   env:
    #     SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
    #     SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}