name: 'WordPress.org plugin directory guidelines'
on: # rebuild any PRs and main branch changes
  # workflow_dispatch:
  # push:
  pull_request:
    # branches:
    # - main

jobs:
  wp-org-plugin-guidelines:
    # The advantage of this approach compared to Bartleby's answer (currently the most upvoted) is that it also works with pull_request_review and pull_request_review_comment events. https://stackoverflow.com/questions/62331829/how-to-get-the-target-branch-of-the-github-pull-request-from-an-actions#comment137155808_62332270
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: wp-cli

      - name: Install latest version of dist-archive-command
        run: wp package install wp-cli/dist-archive-command:dev-main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Make sure to use the same version like WordPress/gutenberg.
          # node-version-file: '.nvmrc'
          node-version: v20.11.1
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: |
          npm run build
          wp dist-archive . ./label-printing.zip
          mkdir tmp-build
          unzip label-printing.zip -d tmp-build
      - name: Run plugin check
        uses: swissspidy/wp-plugin-check-action@main
        with:
          build-dir: './tmp-build/label-printing'
          wp-version: 'trunk'